### PR TITLE
Env/testing #11

### PR DESCRIPTION
**Pull request by Lussier115**
Testing Framework for Unit Testing.

Junit was used to create the unit tests. The test has been integrated with Travis CI as well. The creation of two different folders Test and AndroidTest have been added to be used during the creation of the specific tests. While the Test folder will only contain the unit tests, AndroidTest will be used for integration and acceptance testing. It will be implemented in another issue due to the need for an emulator to run the tests.

Worked with @KrishnaPatel1

### CODE REVIEW

**Comment by lkadian** [comment]
Tried it out and it works nicely. We can merge this for our basic unit test environment while we wait for acceptance/integration tests to be setup.

**Comment by samgo1** [comment]
Merge into development instead of master

**Comment by Lussier115** [comment]
Yeah I had selected develop but probably didn't save properly, just changed it

**Comment by anthonyle17** [comment]
Just tested and works well -- we now need to add 3 unit tests for Issue #12 , other than the sample unit tests in this branch.

**Review by anthonyle17 — COMMENTED** [review]
Just tested and works well -- we now need to add 3 unit tests for Issue #12 , other than the sample unit tests in this branch.

**Pull request merged**
