### PR TITLE
Feat/stamp caption backend #127

### PR DESCRIPTION
**Pull request by aa-software2112**
1. In photo mode, press the "A" icon at the top
2. Write in a caption (the keyboard should automatically open if you press in the text area"
3. Press "stamp" when you're done
4. Check your gallery for the stamp

### CODE REVIEW

**Review by anthonyle17 — COMMENTED** [review]
Can you guys check if the feature looks misplaced/odd positioning on your phones please? Thanks! @Lussier115 @lkadian @KrishnaPatel1

**Review by Lussier115 — COMMENTED** [review]
Tested it and looks good.
Size of the font isn't too small to make it hard to read nor too large to cover the image, good work.

**Comment by KrishnaPatel1** [comment]
It works well, but the stamp is not in the right orientation. I take a picture vertically and it looks like this:

IMG_20190409_151559

**Comment by KrishnaPatel1** [comment]
> It works well, but the stamp is not in the right orientation. I take a picture vertically and it looks like this:
> 
> IMG_20190409_151559

**Comment by aa-software2112** [comment]
> It works well, but the stamp is not in the right orientation. I take a picture vertically and it looks like this:
> 
> IMG_20190409_151559

@lkadian is having this issue too; I will be checking this

**Pull request merged**
