### PR TITLE
Env/add robolectric support 13

### PR DESCRIPTION
**Pull request by aa-software2112**
Support for robolectric testing with a complete example (that initializes the test environment exactly the way we will need it for future testing) is provided. 

I need @KrishnaPatel1  @laurawheatley and @samgo1 to test this locally;

1. Fetch this branch and load it into Android Studio
2. In app>src>test>kotlin, open KotlinRobolectric.kt
3. Click on the button in the image below (wait for Android Studio to finish syncing)
image
5. Run the test. Report the status of the test here (pass or fail).

### CODE REVIEW

**Comment by KrishnaPatel1** [comment]
@aa-software2112 The test didn't work initially. I added the Robolectric package to the gradle file, restarted the test, and they passed. I suggest please link your commit messages to the issue number so that we can track how many commits and contributions are made to each issue. E.g. `[#13] (Commit message)...`

**Comment by samgo1** [comment]
@aa-software2112 The tests passed but I got warning saying `w: Runtime JAR files in the classpath have the version 1.2, which is older than the API version 1.3.` That being said, did you delete your `/.gradle/caches/ ` directory when changing the app dependency to `testImplementation 'org.jetbrains.kotlin:kotlin-stdlib:1.3.0'`?

**Comment by aa-software2112** [comment]
@KrishnaPatel1 the robolectric package was already in the build.grade (application level one), if that was what you're referring to. Moreover, the entire setup (building + tests) ran on Travis with the current branch setup.

**Comment by aa-software2112** [comment]
@samgo1 that warning is fine I believe, I ran "Invalidate Caches / Restart" in Android after all changes were made.

**Comment by samgo1** [comment]
> @samgo1 that warning is file I believe, I ran "Invalidate Caches / Restart" in Android after all changes were made.

Deleting the `$HOME/.gradle/caches` directory did the trick!

**Review by samgo1 — APPROVED** [review]
After testing it locally I approve the changes

**Comment by laurawheatley** [comment]
Tested locally and can confirm the test passed with no problems!

**Review by laurawheatley — APPROVED** [review]
Tested locally and can confirm the test passed with no problems!

**Comment by samgo1** [comment]
@KrishnaPatel1 Do you approve changes?

**Comment by aa-software2112** [comment]
> @aa-software2112 The test didn't work initially. I added the Robolectric package to the gradle file, restarted the test, and they passed. I suggest please link your commit messages to the issue number so that we can track how many commits and contributions are made to each issue. E.g. `[#13] (Commit message)...`

This does not make much sense; if you check the "changes" in this branch, robolectric is now imported twice (once when i had already declared it, another time after you added it). I'm going to remove the second reference you added...

**Pull request merged**
