### PR TITLE
Feat/backend 58

### PR DESCRIPTION
**Pull request by lkadian**
Made the backend changes for UI redesign #44 

   * Swipe in the direction of the arrow to access the photo gallery (left in vertical mode, up in horizontal mode).

   * Change resolution is now on the top row. **I tried making the changes to put it in the settings activity, however it is more tricky than we thought**. The change resolution functionality is highly dependent on CameraPreview view, and only MainActivity should have that view. It would take some pretty big changes on the existing code and might end up breaking stuff. Unless I'm completely missing something which is definitely possible or if someone has a better idea, I don't think we should bother. I had an idea to launch MainActivity and right away prompt for the change resolution dialog when you click the button in the settings, but that didn't work so well, and it's kind of a hacky solution to the problem, since you're not supposed to be able to do that when launching activities

  * Made some additional minor changes to clean up UI and some refactoring to clean up code from countdown timer implementation (tests were refactored accordingly).

### CODE REVIEW

**Review by anthonyle17 — CHANGES_REQUESTED** [review]
Tested and found some glitches:
1. Countdown button 10 and 15 sec do not work anymore. Only 5 sec works.
2. Change Resolution button in Settings does not work.  

Otherwise, the swipe feature works well, nice job. I like the new UI look for the Countdown list options and the new locations for the buttons.

**Comment by lkadian** [comment]
@anthonyle17 

1. I don't have the same issue on my phone, however I think I know why it's happening on your phone, the swipe area is going over the 10 and 15 so you can't select them, need to fix the sizing to be relative, which I will fix!

2.  As I explained in the original post it is trickier than we thought to switch the change resolution dialog in the settings activity. I think it would require a lot of changes to the implementation because right now all the change resolution dialog logic and data is contained in the CameraPreview view, and SettingsActivity should not have that view in it. So basically I decided to not put it in settings and instead I put it in the top row of the MainActivity, so we have 4 icons on the top row. I think it looks clean this way. If someone has a better idea on how to fix it they can let me know, but I couldn't think of a quick solution to this, I don't think it's worth bothering or spending more time with, we could end up breaking things

**Comment by lkadian** [comment]
@anthonyle17 Can you let me know if my latest commit fixed your first issue

**Review by anthonyle17 — APPROVED** [review]
@lkadian Just tested and with your new commit, both the glitches I found are fixed.

- [x] All countdown buttons now function.
- [x] Resolution button in Settings removed-- hence, it is on the main screen, which looks clean indeed!

**Pull request merged**
