### PR TITLE
[#29] Removed linting stage, removed 2 tasks from compile stage

### PR DESCRIPTION
**Pull request by KrishnaPatel1**
I made 3 changes to the travis file:

* Removed the linting stages
* Removed assembleRelease and clean from the compile stage
* Added Ktlint to compile stage

### CODE REVIEW

**Review by samgo1 — COMMENTED** [review]
Good, can you also remove the runUnitTests task completely and instead in the 'test' stage use `./gradlew testDebugUnitTest
`, while we don't have integration testing yet

**Comment by KrishnaPatel1** [comment]
@samgo1 but why change it to `testDebugUnitTest`? `runUnitTests` Does the same thing but future-proofed to that we can add additional steps to the task if we'd like to in the future.

**Comment by samgo1** [comment]
Good point but the name can be misleading, we can think of runUnitTests as a task that runs the test on the debug build and the release build which it does not. A task name like `testDebugUnitTestExtended` should better serve the purpose.

**Comment by KrishnaPatel1** [comment]
You're correct, I'll make a new commit to address that. As in changing the name of the task to `testDebugUnitTestExtended`

**Pull request merged**
