### PR TITLE
Linting setup

### PR DESCRIPTION
**Pull request by KrishnaPatel1**

### CODE REVIEW

**Review by samgo1 — COMMENTED** [review]
I removed the linting work that had been done on ChangeResolutionDialog.kt and ran ./gradlew ktlint from the root of the project to see the expected changes and the build failed.

Please instruct how you made it work, I used jdk-10.0.1

**Comment by aa-software2112** [comment]
I will run this tomorrow, but can you explain to me what the expected behavior is?

**Comment by KrishnaPatel1** [comment]
So basically there are two linting tasks: **Ktlint** and **KtlintFormat**

- **Ktlint**: this task can be run in the terminal via the Graddle command `./gradlew ktlint`. When you run the task, if it finds a formatting error (such as in the case of @samgo1 comment), it **WILL** crash. Therefore, if ktlint crashes it means there is a linting error in the code that you **must absolutely** fix. However, prior to crashing, it will notify you where the error is, what line it is, and what type of error it is. Please refer to the Wiki for additional information on the Ktlint library and other things you may come across.

- **KtlintFormat**: this task can be run in the terminal via the Graddle command `./gradlew ktlintformat`. If this task finds a **non-critical** linting error, it will automatically correct it. This is the case in @samgo1 comment, where the constructor or the  `ChangeResolutionDialog` class did not conform to the coding style. However, for more **critical** errors, the linter will not be able to fix them automatically and it **will** instead **crash** and notify you of what the error is. Such is the case with wildcard imports (detailed example in the wiki). In these cases, you must manually go into the code and fix them, or in my case with the wildcard imports, disable the linter on that specific line. However, I **strongly** discourage disabling the linter for anything other than that. As the linter is there to provide consistency in the coding style. Disabling the linter at too many places will negate its purpose.

**Comment by samgo1** [comment]
Good I ran both tasks and it works 👍 . I'm suggesting that we could add the ktlint task to the travis script to verify that whatever we are pushing to a pull request does not contain lint and before pushing to the repo we should locally run the ./gradlew ktlintFormat to clean the code.

**Comment by KrishnaPatel1** [comment]
Yes, the idea would be for everybody to run **KtlintFormat** at least once before pushing the code. I would suggest even taking an extra step and running KtlintFormat before every gradle build in Android Studio. That way your code will always be lint-free at every new block of functional code written; but, it's up to the individual and it's their responsibility to ensure the code is lint-free prior to push.

**Pull request merged**
