### PR TITLE
[28] Added espresso support and single example test - to be run on ac…

### PR DESCRIPTION
**Pull request by aa-software2112**
Please run an emulator of your choice, and then run the espresso test.
1. In Android Studio, Tools > AVD Manager > + Create New Virtual Device
2. Select the Pixel phone > Next > x86 Images > Pie (API level 28) > Next > Finish
3. In the AVD Manager (that you just opened), press the "Play" button near the virtual device you just created
4. Once the cold boot is done, navigate to app> src > androidTest > kotlin > com.simplemobilet.... > MainActivityTest
5. Run the test (the way you would run a unit test)
6. Select the emulator you just created in the window that pops up
7. Watch the emulator, and report the pass/fail status of the test

Alternatively, if you have an Android device, plug it in and skip to step 5

### CODE REVIEW

**Comment by lkadian** [comment]
Ran the tests using my phone instead of the emulator; and the test failed giving the error "androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: com.simplemobiletools.camera.debug:id/settings"

I changed the line
`Espresso.onView(withId(R.id.settings)).perform(click(), click())`
to only click() once, and now the test passes.

The MainActivity's buttons on the top right can fade out, if they are faded out then yes the settings button needs to be pressed twiced otherwise only once to access the settings.

When I run the test is launches the app and when the app is first launched it's in the "unfaded" state and the settings button only needs to be pressed once, so the test was failing because it pressed once, then tried to press again but couldn't find the settings button (since it was already in the settings menu). Perhaps adding some if-else logic to the test would fix the issue (if its faded out click twice else click once)

Also suggest removing the KotlinJUnitTest2.kt from the androidTest folder now since that was a placeholder.

**Review by lkadian — APPROVED** [review]

**Comment by aa-software2112** [comment]
I will look into this issue. I will either replace the code with something more facile, or look into the if-else logic. Good to hear it works. 

You are correct about the double click logic, on the emulator things are much slower and the setting button fades out before the first click can get in, this is why we needed two

**Comment by lkadian** [comment]
For now we will only use it with the emulator, and it works correctly in that case.

**Comment by samgo1** [comment]
@aa-software2112 please reference the issue # in your commits, it makes it easier to navigate here on github. For example on your last commit you wrote 

> [28] Fixed Linter error

Instead do this: [#28] Fixed Linter error
Apart from that, I can't run the emulator on my personal computer so I didn't test your pr. I do have access to an emulator but not last night.

**Pull request merged**
